"""relationships dont is include in repr.

Revision ID: 2a1c1f11c5d4
Revises: 386b7f60d082
Create Date: 2026-07-22 20:26:03.236152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1c1f11c5d4'
down_revision: Union[str, Sequence[str], None] = '386b7f60d082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('book_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('loan_book_isbn_fkey'), 'loan', type_='foreignkey')
    op.create_foreign_key(None, 'loan', 'books', ['book_id'], ['id'])
    op.drop_column('loan', 'book_isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('book_isbn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.create_foreign_key(op.f('loan_book_isbn_fkey'), 'loan', 'books', ['book_isbn'], ['isbn'])
    op.drop_column('loan', 'book_id')
    # ### end Alembic commands ###
