"""add loans table

Revision ID: 386b7f60d082
Revises: ad70193ccc6f
Create Date: 2026-07-18 20:17:53.580009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386b7f60d082'
down_revision: Union[str, Sequence[str], None] = 'ad70193ccc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(), nullable=False),
    sa.Column('loan_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'LATE', name='loanstatus'), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    # ### end Alembic commands ###
